### ISSUE TITLE
大佬。我运行了一下，报错，试了几个app，每个app报的错误还不同，列出一个错误信息，大佬麻烦看一下

### ISSUE THREAD

**Issue by BoyYongXin** [hluwa/FRIDA-DEXDump#1]
frida.PermissionDeniedError: unable to access process with pid 20541 due to system restrictions; try `sudo sysctl kernel.yama.ptrace_scope=0`, or run Frida as root

是app内部，有检测么

**Comment by hluwa** [comment]
保证Frida可以正常注入进程即可dump。
