### ISSUE TITLE
脱出的hex分好几个文件

### ISSUE THREAD

**Issue by Lex-wa** [hluwa/FRIDA-DEXDump#11]
脱出的hex分好几个文件，是需要合并吗？如果需要合并具体怎么操作？
我测试的一个脱出三个hex文件，前两个能打开，最后一个打开啥也没有，但是文件大小有2M.

**Comment by xiuluo211314** [comment]
同问，多个dex文件是啥意思？应该用一个，还是多个？

**Comment by xiuluo211314** [comment]
脱出的hex分好几个文件，分别拖入到jadx-gui中，查看包名是不是需要的原码。很多个dex文件是因为用了很多的第三方库。

**Comment by hluwa** [comment]
重命名为classes.dex classes1.dex ...， 重新压进apk包再用反编译工具打开即可合并。
