### ISSUE TITLE
过反调试

### ISSUE THREAD

**Issue by K7cl** [hluwa/FRIDA-DEXDump#12]
现在很多壳带反调试，frida附不上。我现在遇到一个厉害的，梆梆的壳。用spawn -f参数都绕不过，打开直接黑屏。大佬有啥好思路一键脱这种壳的dex吗？

**Comment by hluwa** [comment]
换别的思路吧，或者先反反调试。

**Comment by K7cl** [comment]
嗯嗯，我再学习学习，看汇编过反调还不太会
