### ISSUE TITLE
[plugin] C:\Users\kingking\.objection\plugins\dexdump does not appear to be a valid plugin. Missing __init__.py

### ISSUE THREAD

**Issue by kingking888** [hluwa/FRIDA-DEXDump#16]
`C:\Users\jin10>objection -g wind.android explore -P C:\Users\kingking\.objection\plugins
Using USB device `Pixel 2`
Agent injected and responds ok!
[plugin] C:\Users\kingking\.objection\plugins\dexdump does not appear to be a valid plugin. Missing __init__.py
Loaded plugin: wallbreaker

     _   _         _   _
 ___| |_|_|___ ___| |_|_|___ ___
| . | . | | -_|  _|  _| | . |   |
|___|___| |___|___|_| |_|___|_|_|
      |___|(object)inject(ion) v1.9.6

     Runtime Mobile Exploration
        by: @leonjza from @sensepost

[tab] for command suggestions
`

**Comment by hluwa** [comment]
mv C:\Users\kingking.objection\plugins\dexdump\frida_dexdump C:\Users\kingking.objection\plugins\frida_dexdump
rm -rf C:\Users\kingking.objection\plugins\dexdump

**Comment by kingking888** [comment]
大佬，非常感谢！
