### ISSUE TITLE
Did not give runtime loaded DEXs

### ISSUE THREAD

**Issue by Behroozfar-A** [hluwa/FRIDA-DEXDump#17]
The Tool didn't give any runtime loaded DEXs with DexProtector.
Thank you for this Repo.

**Comment by hluwa** [comment]
Which DexProtector?  Can you submit sample?

**Comment by Behroozfar-A** [comment]
[DexProtector](https://dexprotector.com)
[The Sample](https://play.google.com/store/apps/details?id=co.palang.QuizOfKingss) : A persian trivia game, has written with Corona engine and protected with DexProtector

**Comment by hluwa** [comment]
try again with the latest code？

**Comment by Behroozfar-A** [comment]
> try again with the latest code？

Works now.
Thank you for your great job.
