### ISSUE TITLE
360加固的主dex包文件无法反编译打开

### ISSUE THREAD

**Issue by lshAndroid** [hluwa/FRIDA-DEXDump#24]
今年360加固增加了对dex包的加密处理,脱壳出无法解析,请问怎么办,谢谢

**Comment by owen800q** [comment]
@lshAndroid  老哥。可以說下如何解決的嗎，我有同樣的問題？

**Comment by lshAndroid** [comment]
我也没有解决,目前反编译的dex包可能存在缺失,还在验证代码




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "owen800q"<notifications@github.com&gt;; 
发送时间: 2020年12月16日(星期三) 下午5:31
收件人: "hluwa/FRIDA-DEXDump"<FRIDA-DEXDump@noreply.github.com&gt;; 
抄送: "简单"<410011085@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [hluwa/FRIDA-DEXDump] 360加固的主dex包文件无法反编译打开 (#24)





 
@lshAndroid  老哥。可以說下如何解決的嗎，我有同樣的問題？

**Comment by AoEiuV020** [comment]
两年了，现在360加固有办法解吗？
frida解出一堆乱七八糟的就是没有app主要代码，

**Comment by owen800q** [comment]
> 两年了，现在360加固有办法解吗？ frida解出一堆乱七八糟的就是没有app主要代码，

現在加固app基本都沒法脫，都有對抗

**Comment by misslng** [comment]
> > 两年了，现在360加固有办法解吗？ frida解出一堆乱七八糟的就是没有app主要代码，
> 
> 現在加固app基本都沒法脫，都有對抗

现在这个 被淘汰了吗

**Comment by AoEiuV020** [comment]
frida没有，360免费加固的我用frida解了，
riru-fridainstaller

wssbwssbwssb ***@***.***> 于 2023年3月11日周六 17:47写道：
