### ISSUE TITLE
[Except] - Unable to inject into process: 'NoneType' object has no attribute 'pid' in

### ISSUE THREAD

**Issue by websecer** [hluwa/frida-dexdump#36]
[Except] - Unable to inject into process: 'NoneType' object has no attribute 'pid' in
  File "main.py", line 147, in choose
    return target.pid, target.identifier

**Comment by DeveKing7** [comment]
[Except] - Unable to inject into process: 'NoneType' object has no attribute 'pid' in 
  File "/Library/Python/2.7/site-packages/frida_dexdump/main.py", line 153, in choose
    return target.pid, target.identifier

**Comment by t0hka1** [comment]
[Except] - Unable to inject into process: 'NoneType' object has no attribute 'pid' in
  File "main.py", line 153, in choose
    return target.pid, target.identifier

**Comment by BBNO** [comment]
[Except] - Unable to inject into process: 'NoneType' object has no attribute 'pid' in
  File "main.py", line 153, in choose
    return target.pid, target.identifier
