### ISSUE TITLE
这里没看明白为啥是4096？谢谢

### ISSUE THREAD

**Issue by chaolei-peng** [hluwa/FRIDA-DEXDump#39]
![image](https://user-images.githubusercontent.com/16797866/132319409-75496d20-a991-43d6-800f-534eae849b2e.png)

**Comment by hluwa** [comment]
注释里已经写了， TYPE_MAP_LIST == 4096， 更加详细的可以去看 DEX 文件格式

**Comment by chaolei-peng** [comment]
1
