### ISSUE TITLE
如何使用frida的参数？例如 frida-server --host 192.168.0.100 ? 

### ISSUE THREAD

**Issue by sg552** [hluwa/FRIDA-DEXDump#40]
貌似 python3 main.py 这个命令运行之后，是按照 `frida-ps --usb` 这个默认命令来的。
我再虚拟机（vmware）上的usb设备无法访问。

所以，想了解下，如何在frida-dexdump 中，为frida-ps 这个命令增加 --host参数。谢谢。
（现在的报错是：unable to connect to remote server）

![图片](https://user-images.githubusercontent.com/234533/139650035-9aeaa4ca-c48e-4c2e-b18d-61a51438cc71.png)

**Comment by hluwa** [comment]
这个开源仓库没有这个功能， 可以自己改一下源码

>

**Comment by sg552** [comment]
@hluwa 感谢回复，其实您这个项目非常棒，我看看日后我能否有机会贡献一点力量。

这个问题出现的原因是我在 host: win10 的 虚拟机上（ubuntu18），运行了frida client, 然后把一个安卓机，连接到了这个 虚拟机上，导致了 frida server( android ) 与 frida client( vm ubuntu 18 )之间无法通过默认的 usb方式通讯， 但是倒可以使用 192.168.0.x 这样的局域网方式连接。

后来我抛弃虚拟机，直接使用安卓与物理机连接，就好了。

**Comment by sg552** [comment]
solution: use physical host, not a vm-ware host, then problems gone.
