### ISSUE TITLE
中文应用名脱壳失败

### ISSUE THREAD

**Issue by moondrink** [hluwa/frida-dexdump#43]
环境：frida 15.1.2，对象顺丰速运
在choose函数中target.identifier的值是包名
Application(identifier="com.sf.activity", name="顺丰速运", pid=14246, parameters={})
但是在device.enumerate_processes()中process的name值却是“顺丰速运”，而非包名"com.sf.activity"，导致匹配失败。
建议在choose函数处理如下
if pid is None and pkg is None:
        target = device.get_frontmost_application()
        pid = target.pid
        #return target.pid, target.identifier

**Comment by Easy-Ez** [comment]
-n 顺丰速运 设置下包名
