### ISSUE TITLE
frida-dexdump version not providing expected number

### ISSUE THREAD

**Issue by cryptax** [hluwa/frida-dexdump#52]
This is a minor issue.

I have frida-dexdump **2.0.1:**

```
$ pip list | grep dexdump
frida-dexdump  2.0.1
```

But if I do `frida-dexdump --version`, it says **15.1.17**, which is _Frida_'s version.

The program's help says:

```
 --version             show program's version number and exit
 ```
 So, with this comment, I think that we should get `2.0.1`. If not, it's just as simple as modifying the help with something like "show Frida's version number and exit"

**Comment by hluwa** [comment]
Thank you, fixed in [#f81257ecf9408e604d40f41f49711b2d6e42df12](https://github.com/hluwa/frida-dexdump/commit/f81257ecf9408e604d40f41f49711b2d6e42df12) :)
