### ISSUE TITLE
phone crash

### ISSUE THREAD

**Issue by Kerrbty** [hluwa/frida-dexdump#55]
DEVICE: nexus 5X , SYSTEM: 6.0.1 (MMB29K)
CLIENT: 15.1.17,   SERVER:  frida-server-15.1.17-android-arm64 
COMMAND: frida-ps -U
CAUSE: Android UI  Crash

error log:
{"type":"error","description":"RangeError: Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded\n    at Proxy.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:722:1)\n    at frida/node_modules/frida-java-bridge/lib/class-factory.js:627:1\n    at Array.forEach (<anonymous>)\n    at ne (frida/node_modules/frida-java-bridge/lib/class-factory.js:624:1)\n    at CallbackContext.<anonymous> (frida/node_modules/frida-java-bridge/lib/class-factory.js:592:1)\n    at Function.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:1058:1)\n    at Proxy.e (frida/node_modules/frida-java-bridge/lib/class-factory.js:580:1)\n    at Function.value (frida/node_modules/frida-java-bridge/lib/class-factory.js:964:1)\n    at Proxy.e (frida/node_modules/frida-java-bridge/lib/class-factory.js:547:1)\n    at Proxy.sendMessageDelayed.implementation (/internal-agent.js:443:31)","fileName":"frida/node_modules/frida-java-bridge/lib/class-factory.js","lineNumber":722,"columnNumber":1}

**Comment by hluwa** [comment]
Please submit https://github.com/frida/frida/issues, thanks.
