### ISSUE TITLE
frida 的版本 和模拟器安卓版本 推荐一下

### ISSUE THREAD

**Issue by CL545740896** [hluwa/FRIDA-DEXDump#7]
frida 的版本 和模拟器安卓版本 推荐一下

**Comment by CL545740896** [comment]
360加固的 用你这个脱不出来
03-03/15:47:25 INFO [DEXDump]: DexSize=0x2e648c, SavePath=F:\逆向\FRIDA-DEXDump/
com.example.com.qqsg/0x961f54fc.dex
03-03/15:47:25 INFO [DEXDump]: DexSize=0x507314, SavePath=F:\逆向\FRIDA-DEXDump/
com.example.com.qqsg/0x9c56053c.dex
03-03/15:47:25 INFO [DEXDump]: DexSize=0x11c, SavePath=F:\逆向\FRIDA-DEXDump/com
.example.com.qqsg/0x9cc3dace.dex
03-03/15:47:25 INFO [DEXDump]: DexSize=0x1, SavePath=F:\逆向\FRIDA-DEXDump/com.e
xample.com.qqsg/0x9cc3e2c1.dex
03-03/15:47:25 INFO [DEXDump]: DexSize=0x507314, SavePath=F:\逆向\FRIDA-DEXDump/
com.example.com.qqsg/0x9ce7a53c.dex

**Comment by CL545740896** [comment]
运行环境 雷电模拟器 7.1.2 
F:\逆向\FRIDA-DEXDump>frida --version
12.7.22

**Comment by hluwa** [comment]
用真机。

**Comment by vanehu** [comment]
机器需要root嘛
